"""
Cython compilation script for the backend package.

Compiles all .py files under app/ into platform-native extension modules
(.pyd on Windows, .so on Linux) and outputs them to backend/dist/.
Source .py files under backend/app/ are left intact.

Usage:
    python setup_cython.py build_ext --build-lib dist

Requires:
    pip install cython
    A C compiler (MSVC on Windows, gcc/clang on Linux)
"""

import os
import shutil
import sys
from pathlib import Path

from setuptools import setup
from Cython.Build import cythonize
from Cython.Distutils import build_ext

HERE = Path(__file__).resolve().parent
APP_DIR = HERE / "app"
DIST_DIR = HERE / "dist"

# Files that must remain as .py (entry points loaded via -m or import strings)
# main.py is the FastAPI app entry point (uvicorn app.main:app)
# bootstrap.py is imported by init scripts (python -m app.db.bootstrap --schema)
# land_parcel_repository.py and data_import_service.py are kept editable
KEEP_AS_PY = {
    "app/main.py",
    "app/db/bootstrap.py",
    "app/repositories/land_parcel_repository.py",
    "app/services/data_import_service.py",
}

# Directories containing non-Python runtime files that must be copied to dist/
COPY_DIRS = [
    "app/workflows",
    "app/storage",
]


def collect_py_files(root: Path) -> list[str]:
    """Collect all .py files relative to HERE."""
    files = []
    for py_file in root.rglob("*.py"):
        rel = str(py_file.relative_to(HERE)).replace("\\", "/")
        files.append(rel)
    return files


def copy_kept_files(compile_files: list[str], keep_files: list[str]) -> None:
    """Copy kept .py files and non-Python directories into dist/."""
    # Copy kept .py files preserving directory structure
    for py_rel in keep_files:
        src = HERE / py_rel
        dst = DIST_DIR / py_rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(str(src), str(dst))
        print(f"  Kept .py: {py_rel}")

    # Copy non-Python directories
    for dir_rel in COPY_DIRS:
        src_dir = HERE / dir_rel
        if src_dir.is_dir():
            dst_dir = DIST_DIR / dir_rel
            if dst_dir.exists():
                shutil.rmtree(str(dst_dir))
            shutil.copytree(str(src_dir), str(dst_dir))
            print(f"  Copied dir: {dir_rel}")


def main():
    # Clean previous dist
    if DIST_DIR.exists():
        shutil.rmtree(str(DIST_DIR))
    DIST_DIR.mkdir(parents=True, exist_ok=True)

    py_files = collect_py_files(APP_DIR)

    # Separate files to compile vs keep as .py
    compile_files = [f for f in py_files if f not in KEEP_AS_PY]
    keep_files = [f for f in py_files if f in KEEP_AS_PY]

    if not compile_files:
        print("No .py files to compile.")
        copy_kept_files(compile_files, keep_files)
        return

    print(f"Compiling {len(compile_files)} files with Cython...")
    print(f"Keeping {len(keep_files)} files as .py: {keep_files}")
    print(f"Output directory: {DIST_DIR}")
    print()

    setup(
        name="ruralland_backend_build",
        ext_modules=cythonize(
            compile_files,
            compiler_directives={
                "language_level": "3",
                "binding": True,
                "annotation_typing": False,
            },
            build_dir=str(HERE / "build" / "cython_cache"),
            nthreads=os.cpu_count() or 4,
        ),
        script_args=["build_ext", "--build-lib", str(DIST_DIR)],
        cmdclass={"build_ext": build_ext},
    )

    # Copy kept .py files and non-Python dirs to dist/
    copy_kept_files(compile_files, keep_files)

    # Clean up intermediate .c files generated by Cython
    for py_rel in compile_files:
        c_file = HERE / py_rel.replace(".py", ".c")
        if c_file.exists():
            c_file.unlink()

    print()
    print("Backend compilation complete.")
    print(f"  Compiled: {len(compile_files)} modules → .pyd/.so")
    print(f"  Kept .py: {len(keep_files)} entry modules")
    print(f"  Output:   {DIST_DIR}")
    print()
    print("Source .py files under backend/app/ are preserved.")


if __name__ == "__main__":
    main()
